import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/Header";
import "./globals.css";

import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Product App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-gray-200">
        <Header />
        <div className="flex bg-sky-600   h-screen-minus-128">
          <Sidebar />
          <div className="bg-gray-600 w-full z-0 overflow-y-auto h-screen-minus-128  ">
            {children}
            <ToastContainer position="top-center" autoClose={2000} />
          </div>
        </div>
        <div className="bg-sky-600 flex justify-center items-center h-16 ">
          <h1 className="font-semibold  text-xl py-3 text-center">Footer</h1>
        </div>
      </body>
    </html>
  );
}
